# Generated by Django 3.0.8 on 2020-07-05 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200705_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 7, 5, 14, 10, 20, 949681, tzinfo=utc))),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
