# Generated by Django 3.0.8 on 2020-07-05 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200705_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 14, 16, 3, 56254, tzinfo=utc)),
        ),
    ]
